repos:
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
    - id: remove-crlf
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: mixed-line-ending
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.94.1
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
      args:
        - --hook-config=--retry-once-with-cleanup=true
    - id: terraform_docs
      args:
        - --args=--lockfile=false
    - id: terraform_tflint
      args:
        - --args=--color
        - --args=--call-module-type=all
        - --args=--fix
